import "./globals.css";
import Navbar from "./nav/Navbar";
import ToasterProvider from "./provider/ToasterProvider";

export const metadata = {
  title: "Auction App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ToasterProvider />
        <Navbar/>
          <main className='container mx-auto px-5 pt-10'>
            {children}
          </main>
      </body>
    </html>
  );
}
